source: app
destination: build
baseurl: ''

title: EuRuKo 2016, Sofia
email: about@euruko2016.org

description: >
  EuRuKo is an annual ruby conference in Europe. Visit Sofia, Bulgaria on
  September 23—24, 2016.

twitter_username: euruko
github_username:  euruko

# Build settings
markdown: kramdown

