source: app
destination: build

title: EuRuKo 2016, Sofia
email: about@euruko2016.org

description: >
  EuRuKo is an annual ruby conference in Europe. Visit Sofia, Bulgaria on
  September 23—24, 2016.

  # this means to ignore newlines until "baseurl:"
  Google search results) and in your feed.xml site description.

twitter_username: euruko
github_username:  euruko

# Build settings
markdown: kramdown
